# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""Freeze TurboQuant codebooks and FWHT signs from the pinned reference.

The codec must not regenerate its constants at runtime (numpy RNG streams and
scipy special functions are not guaranteed stable across versions), so this
script runs ``turboquant_plus`` at a pinned commit once and writes the results
as float64 hex literals plus sha256 digests into ``constants.py``.

Usage:

    python scripts/llm/turboquant/generate_constants.py \
        --reference-repo ~/git/turboquant_plus

    # CI-style check that the committed file is current:
    python scripts/llm/turboquant/generate_constants.py \
        --reference-repo ~/git/turboquant_plus --check
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

import numpy as np

REFERENCE_URL = "https://github.com/TheTom/turboquant_plus"
REFERENCE_COMMIT = "ba52ad107d1fdd02bc9be8fd85308226b75c905b"
BLOCK_SIZE = 128
BIT_WIDTHS = (3, 4)
# Reference KVCacheCompressor policy: K uses seed, V uses seed + 500.
SEEDS = (42, 542)

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = (
    REPO_ROOT / "src/qai_hub_models/models/templates/llm/turboquant/constants.py"
)

HEADER = """\
# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""


def load_reference_module(repo: Path, rel_path: str, workdir: Path) -> ModuleType:
    source = subprocess.run(
        ["git", "-C", str(repo), "show", f"{REFERENCE_COMMIT}:{rel_path}"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    target = workdir / Path(rel_path).name
    target.write_text(source)
    spec = importlib.util.spec_from_file_location(f"tqp_{target.stem}", target)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def codebook_sha256(centroids: np.ndarray) -> str:
    return hashlib.sha256(centroids.astype("<f8").tobytes()).hexdigest()


def signs_sha256(signs1: np.ndarray, signs2: np.ndarray) -> str:
    payload = signs1.astype(np.int8).tobytes() + signs2.astype(np.int8).tobytes()
    return hashlib.sha256(payload).hexdigest()


def signs_to_str(signs: np.ndarray) -> str:
    return "".join("+" if s > 0 else "-" for s in signs)


def render(repo: Path) -> str:
    with tempfile.TemporaryDirectory(dir="/tmp/claude") as tmp:
        codebook = load_reference_module(repo, "turboquant/codebook.py", Path(tmp))
        rotation = load_reference_module(repo, "turboquant/rotation.py", Path(tmp))

        codebook_lines = []
        codebook_hash_lines = []
        for bits in BIT_WIDTHS:
            centroids = np.asarray(
                codebook.optimal_centroids(bits, BLOCK_SIZE), dtype=np.float64
            )
            hex_values = ",\n".join(f'        "{float(c).hex()}"' for c in centroids)
            codebook_lines.append(
                f"    ({bits}, {BLOCK_SIZE}): (\n{hex_values},\n    ),"
            )
            codebook_hash_lines.append(
                f'    ({bits}, {BLOCK_SIZE}): "{codebook_sha256(centroids)}",'
            )

        sign_lines = []
        sign_hash_lines = []
        for seed in SEEDS:
            signs1, signs2, padded = rotation.random_rotation_fast(
                BLOCK_SIZE, np.random.default_rng(seed)
            )
            assert padded == BLOCK_SIZE
            sign_lines.append(
                f"    ({seed}, {BLOCK_SIZE}): (\n"
                f'        "{signs_to_str(signs1)}",\n'
                f'        "{signs_to_str(signs2)}",\n'
                "    ),"
            )
            sign_hash_lines.append(
                f'    ({seed}, {BLOCK_SIZE}): "{signs_sha256(signs1, signs2)}",'
            )

    nl = "\n"
    return f'''{HEADER}"""Frozen TurboQuant codec constants.

Generated by ``scripts/llm/turboquant/generate_constants.py`` from turboquant_plus
({REFERENCE_URL}, Apache-2.0, Copyright 2026 Tom Turney) at commit
{REFERENCE_COMMIT}. Do not edit by hand.

- ``CODEBOOK_HEX[(bits, d)]``: ``turboquant.codebook.optimal_centroids(bits, d)``,
  float64, ascending. Digest is sha256 of the little-endian float64 bytes.
- ``FWHT_SIGNS[(seed, d)]``: ``turboquant.rotation.random_rotation_fast(d,
  np.random.default_rng(seed))`` as ``(signs1, signs2)``, ``+`` = +1. Digest is
  sha256 of ``int8(signs1) + int8(signs2)``.
"""

from __future__ import annotations

REFERENCE_URL = "{REFERENCE_URL}"
REFERENCE_COMMIT = "{REFERENCE_COMMIT}"

CODEBOOK_HEX: dict[tuple[int, int], tuple[str, ...]] = {{
{nl.join(codebook_lines)}
}}

CODEBOOK_SHA256: dict[tuple[int, int], str] = {{
{nl.join(codebook_hash_lines)}
}}

FWHT_SIGNS: dict[tuple[int, int], tuple[str, str]] = {{
{nl.join(sign_lines)}
}}

FWHT_SIGNS_SHA256: dict[tuple[int, int], str] = {{
{nl.join(sign_hash_lines)}
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-repo", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the output file differs instead of rewriting it.",
    )
    args = parser.parse_args()

    Path("/tmp/claude").mkdir(parents=True, exist_ok=True)
    rendered = render(args.reference_repo.expanduser())
    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != rendered:
            print(f"{args.output} is stale; rerun without --check.")
            sys.exit(1)
        print(f"{args.output} matches turboquant_plus@{REFERENCE_COMMIT}.")
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
