# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""Frozen TurboQuant codec constants.

Generated by ``scripts/llm/turboquant/generate_constants.py`` from turboquant_plus
(https://github.com/TheTom/turboquant_plus, Apache-2.0, Copyright 2026 Tom Turney) at commit
ba52ad107d1fdd02bc9be8fd85308226b75c905b. Do not edit by hand.

- ``CODEBOOK_HEX[(bits, d)]``: ``turboquant.codebook.optimal_centroids(bits, d)``,
  float64, ascending. Digest is sha256 of the little-endian float64 bytes.
- ``FWHT_SIGNS[(seed, d)]``: ``turboquant.rotation.random_rotation_fast(d,
  np.random.default_rng(seed))`` as ``(signs1, signs2)``, ``+`` = +1. Digest is
  sha256 of ``int8(signs1) + int8(signs2)``.
"""

from __future__ import annotations

REFERENCE_URL = "https://github.com/TheTom/turboquant_plus"
REFERENCE_COMMIT = "ba52ad107d1fdd02bc9be8fd85308226b75c905b"

CODEBOOK_HEX: dict[tuple[int, int], tuple[str, ...]] = {
    (2, 128): (
        "-0x1.1156d5a2f6bdep-3",
        "-0x1.4801cd29f4e3ep-5",
        "0x1.4801cd29f4e3ep-5",
        "0x1.1156d5a2f6bdep-3",
    ),
    (3, 128): (
        "-0x1.858b2cd5842dcp-3",
        "-0x1.e68bff867eed5p-4",
        "-0x1.11b3f4e3e7e27p-4",
        "-0x1.62ef1ac4720e3p-6",
        "0x1.62ef1ac4720e9p-6",
        "0x1.11b3f4e3e7e27p-4",
        "0x1.e68bff867eed7p-4",
        "0x1.858b2cd5842dcp-3",
    ),
    (4, 128): (
        "-0x1.ebf3457eaba56p-3",
        "-0x1.737a065915ac3p-3",
        "-0x1.21c6b52382be7p-3",
        "-0x1.c0e9c17a9cb2ap-4",
        "-0x1.500f7b61de4cep-4",
        "-0x1.d3a9e85333318p-5",
        "-0x1.1400a5795469dp-5",
        "-0x1.6d1229a612468p-7",
        "0x1.6d1229a61243ep-7",
        "0x1.1400a579546a1p-5",
        "0x1.d3a9e85333313p-5",
        "0x1.500f7b61de4cfp-4",
        "0x1.c0e9c17a9cb1dp-4",
        "0x1.21c6b52382bf6p-3",
        "0x1.737a065915ab2p-3",
        "0x1.ebf3457eaba52p-3",
    ),
    (5, 128): (
        "-0x1.160fc9331d2d5p-2",
        "-0x1.c02fd9d426792p-3",
        "-0x1.79957d49df67cp-3",
        "-0x1.437429c148c74p-3",
        "-0x1.16f3d4ee1aa96p-3",
        "-0x1.e1dab0578ff5fp-4",
        "-0x1.9f45e4db33641p-4",
        "-0x1.63fcb02034de0p-4",
        "-0x1.2e80dc1399869p-4",
        "-0x1.fb6c959b5b5b4p-5",
        "-0x1.a17667a68a315p-5",
        "-0x1.4da415a9afd3cp-5",
        "-0x1.fd52643641454p-6",
        "-0x1.66b05a5595dc6p-6",
        "-0x1.aa6024c19d12ap-7",
        "-0x1.1ae8587518bddp-8",
        "0x1.1ae8587518c08p-8",
        "0x1.aa6024c19d0fap-7",
        "0x1.66b05a5595dc6p-6",
        "0x1.fd52643641446p-6",
        "0x1.4da415a9afd32p-5",
        "0x1.a17667a68a32dp-5",
        "0x1.fb6c959b5b5b1p-5",
        "0x1.2e80dc1399875p-4",
        "0x1.63fcb02034dd9p-4",
        "0x1.9f45e4db33634p-4",
        "0x1.e1dab0578ff34p-4",
        "0x1.16f3d4ee1aa89p-3",
        "0x1.437429c148c4fp-3",
        "0x1.79957d49df64fp-3",
        "0x1.c02fd9d4267a1p-3",
        "0x1.160fc9331d2cep-2",
    ),
    (6, 128): (
        "-0x1.2ca6fe06665fdp-2",
        "-0x1.f4978e1c67424p-3",
        "-0x1.b3c0275aeb115p-3",
        "-0x1.82d27d7e3c3d1p-3",
        "-0x1.5b43788de9741p-3",
        "-0x1.3a0fb037f73b2p-3",
        "-0x1.1d8d738d90160p-3",
        "-0x1.04b3b30bcc0ffp-3",
        "-0x1.dd9b63a711dc9p-4",
        "-0x1.b6ae08d930576p-4",
        "-0x1.93d20bde440a9p-4",
        "-0x1.7461796c4ef6ap-4",
        "-0x1.57d244621b89dp-4",
        "-0x1.3daf994a99c08p-4",
        "-0x1.2595d1dbb33b5p-4",
        "-0x1.0f2fd56c0c60cp-4",
        "-0x1.f46a6efb6727dp-5",
        "-0x1.ccd165f65f8a8p-5",
        "-0x1.a72d9fbbe4cd3p-5",
        "-0x1.83293ad724327p-5",
        "-0x1.607cf6eaa2434p-5",
        "-0x1.3eedea30f8285p-5",
        "-0x1.1e4b64910df40p-5",
        "-0x1.fcda145a675dbp-6",
        "-0x1.be6257320bf61p-6",
        "-0x1.80f6ba8780330p-6",
        "-0x1.446696ec075d0p-6",
        "-0x1.08878a4e9be0dp-6",
        "-0x1.9a67d8414f34fp-7",
        "-0x1.24931e5fd9597p-7",
        "-0x1.5ea301f7db644p-8",
        "-0x1.d3373610755fbp-10",
        "0x1.d337361075b7ap-10",
        "0x1.5ea301f7db724p-8",
        "0x1.24931e5fd96d6p-7",
        "0x1.9a67d8414f235p-7",
        "0x1.08878a4e9be45p-6",
        "0x1.446696ec07576p-6",
        "0x1.80f6ba87803e4p-6",
        "0x1.be6257320befdp-6",
        "0x1.fcda145a6760ep-6",
        "0x1.1e4b64910df59p-5",
        "0x1.3eedea30f8285p-5",
        "0x1.607cf6eaa23fdp-5",
        "0x1.83293ad7242f8p-5",
        "0x1.a72d9fbbe4c61p-5",
        "0x1.ccd165f65f870p-5",
        "0x1.f46a6efb67273p-5",
        "0x1.0f2fd56c0c603p-4",
        "0x1.2595d1dbb3396p-4",
        "0x1.3daf994a99c00p-4",
        "0x1.57d244621b8bep-4",
        "0x1.7461796c4ef87p-4",
        "0x1.93d20bde440a8p-4",
        "0x1.b6ae08d930541p-4",
        "0x1.dd9b63a711e0dp-4",
        "0x1.04b3b30bcc111p-3",
        "0x1.1d8d738d9017fp-3",
        "0x1.3a0fb037f73b1p-3",
        "0x1.5b43788de9742p-3",
        "0x1.82d27d7e3c3b4p-3",
        "0x1.b3c0275aeb118p-3",
        "0x1.f4978e1c6747ep-3",
        "0x1.2ca6fe06665d4p-2",
    ),
}

CODEBOOK_SHA256: dict[tuple[int, int], str] = {
    (2, 128): "88258c1b2f4f5053aed4482e59c0ad6d35d9e081130d9829cdc6540b055c7b9a",
    (3, 128): "5d03648f22b4824350be74b68224644c757385477d07eae8dfa3afe98cb2e455",
    (4, 128): "2260ac9861ecc11872763ac359673e54e76be620463948dfaa105f97c1a07740",
    (5, 128): "c6e4c5d739dda7d13d1747230a87b74503beb88c6a6504fe4aff2e30a0492fcc",
    (6, 128): "022b0d83fa9afd56f1e37da122b737d9ae606f7c7bf91def7cc5fd26984c8f2d",
}

FWHT_SIGNS: dict[tuple[int, int], tuple[str, str]] = {
    (42, 128): (
        "-++--+-+--+++++++-+-+--+++-++----++-++-+-++--+-++++-----+-++++-+--+---+---+---+++--+++--++-++-+--++-+-+-++++-+-++-++-----++-++-+",
        "++++-++-+---+---++--+-+-+--+-+++++---+------+++-+-+++--+------+++-+----+-+-+--++-+-++-+----+--+-+-+++--+-+-++--+-+-++-+-+-----+-",
    ),
    (542, 128): (
        "++++----++-+++-+--++-++++-+-+-++---+--+--++-++----+--++--+-+---+++-++-+-+-++---+-----++-++++-+++-+----++-++-++++--+-++-+--++++++",
        "-++++-+-+++-+----+--++-+++-+-+---+--+-++--+----++--++---+-+--+----+--+++-----+-+-++----++-++--++-+--++-+--+----++++-++------+---",
    ),
}

FWHT_SIGNS_SHA256: dict[tuple[int, int], str] = {
    (42, 128): "49847ad511f6a5ef144adc61803db50cbc7c1e6d8ea9b15678cc4d4da7ccdaf3",
    (542, 128): "c41c124d07d9dc3b561daa9984b1ec9de6a2edf681db090e0f12fe5c985dbedb",
}
