# ---------------------------------------------------------------------
# Copyright (c) 2026 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""Frozen TurboQuant codec constants.

Generated by ``scripts/llm/turboquant/generate_constants.py`` from turboquant_plus
(https://github.com/TheTom/turboquant_plus, Apache-2.0, Copyright 2026 Tom Turney) at commit
ba52ad107d1fdd02bc9be8fd85308226b75c905b. Do not edit by hand.

- ``CODEBOOK_HEX[(bits, d)]``: ``turboquant.codebook.optimal_centroids(bits, d)``,
  float64, ascending. Digest is sha256 of the little-endian float64 bytes.
- ``FWHT_SIGNS[(seed, d)]``: ``turboquant.rotation.random_rotation_fast(d,
  np.random.default_rng(seed))`` as ``(signs1, signs2)``, ``+`` = +1. Digest is
  sha256 of ``int8(signs1) + int8(signs2)``.
"""

from __future__ import annotations

REFERENCE_URL = "https://github.com/TheTom/turboquant_plus"
REFERENCE_COMMIT = "ba52ad107d1fdd02bc9be8fd85308226b75c905b"

CODEBOOK_HEX: dict[tuple[int, int], tuple[str, ...]] = {
    (3, 128): (
        "-0x1.858b2cd5842dcp-3",
        "-0x1.e68bff867eed5p-4",
        "-0x1.11b3f4e3e7e27p-4",
        "-0x1.62ef1ac4720e3p-6",
        "0x1.62ef1ac4720e9p-6",
        "0x1.11b3f4e3e7e27p-4",
        "0x1.e68bff867eed7p-4",
        "0x1.858b2cd5842dcp-3",
    ),
    (4, 128): (
        "-0x1.ebf3457eaba56p-3",
        "-0x1.737a065915ac3p-3",
        "-0x1.21c6b52382be7p-3",
        "-0x1.c0e9c17a9cb2ap-4",
        "-0x1.500f7b61de4cep-4",
        "-0x1.d3a9e85333318p-5",
        "-0x1.1400a5795469dp-5",
        "-0x1.6d1229a612468p-7",
        "0x1.6d1229a61243ep-7",
        "0x1.1400a579546a1p-5",
        "0x1.d3a9e85333313p-5",
        "0x1.500f7b61de4cfp-4",
        "0x1.c0e9c17a9cb1dp-4",
        "0x1.21c6b52382bf6p-3",
        "0x1.737a065915ab2p-3",
        "0x1.ebf3457eaba52p-3",
    ),
}

CODEBOOK_SHA256: dict[tuple[int, int], str] = {
    (3, 128): "5d03648f22b4824350be74b68224644c757385477d07eae8dfa3afe98cb2e455",
    (4, 128): "2260ac9861ecc11872763ac359673e54e76be620463948dfaa105f97c1a07740",
}

FWHT_SIGNS: dict[tuple[int, int], tuple[str, str]] = {
    (42, 128): (
        "-++--+-+--+++++++-+-+--+++-++----++-++-+-++--+-++++-----+-++++-+--+---+---+---+++--+++--++-++-+--++-+-+-++++-+-++-++-----++-++-+",
        "++++-++-+---+---++--+-+-+--+-+++++---+------+++-+-+++--+------+++-+----+-+-+--++-+-++-+----+--+-+-+++--+-+-++--+-+-++-+-+-----+-",
    ),
    (542, 128): (
        "++++----++-+++-+--++-++++-+-+-++---+--+--++-++----+--++--+-+---+++-++-+-+-++---+-----++-++++-+++-+----++-++-++++--+-++-+--++++++",
        "-++++-+-+++-+----+--++-+++-+-+---+--+-++--+----++--++---+-+--+----+--+++-----+-+-++----++-++--++-+--++-+--+----++++-++------+---",
    ),
}

FWHT_SIGNS_SHA256: dict[tuple[int, int], str] = {
    (42, 128): "49847ad511f6a5ef144adc61803db50cbc7c1e6d8ea9b15678cc4d4da7ccdaf3",
    (542, 128): "c41c124d07d9dc3b561daa9984b1ec9de6a2edf681db090e0f12fe5c985dbedb",
}
